<?php
$tours = [
    [
        'name' => 'Hilton Istanbul Bosphorus',
        'country' => "Турція",
        'stars' => "5",
        'price' => "1125",
        'transport' => "Літак",
        'imageSrc' => "./assets/hotels_images/Hilton-Istanbul-Bosphorus.jpg",
    ],
    [
        'name' => 'Bellis Deluxe Hotel',
        'country' => "Турція",
        'stars' => "5",
        'price' => "2302",
        'transport' => "Літак",
        'imageSrc' => "./assets/hotels_images/Bellis-Deluxe-Hotel.jpg",
    ],
    [
        'name' => 'Hilton Rijeka Costabella Beach Resort And Spa',
        'country' => "Хорватія",
        'stars' => "5",
        'price' => "1305",
        'transport' => "Автобус",
        'imageSrc' => "./assets/hotels_images/Hilton-Rijeka-Costabella-Beach-Resort-&-Spa.jpg",
    ],
    [
        'name' => 'StaysPro - Glamorous Beverlywood Residence Near',
        'country' => "США",
        'stars' => "4",
        'price' => "1914",
        'transport' => "Літак",
        'imageSrc' => "./assets/hotels_images/StaysPro-Glamorous-Beverlywood-Residence-Near.jpg",
    ],
    [
        'name' => 'Hotel Podgorie Spa',
        'country' => "Україна",
        'stars' => "3",
        'price' => "543",
        'transport' => "Поїзд",
        'imageSrc' => "./assets/hotels_images/Hotel-Podgorie-Spa.jpg",
    ],
    [
        'name' => 'Villa-des-Prés',
        'country' => "Франція",
        'stars' => "5",
        'price' => "4651",
        'transport' => "Літак",
        'imageSrc' => "./assets/hotels_images/Villa-des-Prés.jpg",
    ],
    [
        'name' => "Hôtel Dali Val d'Europe",
        'country' => "Франція",
        'stars' => "4",
        'price' => "681",
        'transport' => "Літак",
        'imageSrc' => "./assets/hotels_images/chanteloup-en-brie-pic-61.jfif"
    ],
    [
        'name' => 'Number 21 by DBI',
        'country' => "Україна",
        'stars' => "4",
        'price' => "404",
        'transport' => "Поїзд",
        'imageSrc' => "./assets/hotels_images/Number-21-by-DBI.jpg",
    ],
    [
        'name' => 'Villa Istra Relax Smaragd',
        'country' => "Хорватія",
        'stars' => "4",
        'price' => "1301",
        'transport' => "Автобус",
        'imageSrc' => "./assets/hotels_images/Villa-Istra-Relax-Smaragd.jpg",
    ],
];
